##############################################################################
# nabu-relay module — cloud-agnostic relay configuration generator
#
# This module does NOT create cloud resources. It generates:
#   - cloud-init user-data script (output: user_data)
#   - A rendered nabu relay config snippet (output: nabu_config_snippet)
#
# The caller (oci/ or hetzner/) is responsible for passing in the instance's
# public IP after resource creation.
##############################################################################

variable "public_ip" {
  description = "Public IPv4 address of the relay instance (provided by the caller)"
  type        = string
  default     = ""
}

locals {
  probe_port = var.listen_port + var.probe_port_offset

  user_data = <<-EOT
    #!/bin/bash
    set -euo pipefail

    # ------------------------------------------------------------------
    # NABU relay bootstrap — generated by Terraform nabu-relay module
    # relay  : ${var.relay_name}
    # path-id: ${var.path_id}
    # region : ${var.region_label}
    # ------------------------------------------------------------------

    apt-get update -qq
    apt-get install -y -qq docker.io ufw

    # Firewall rules
    ufw --force enable
    ufw allow ssh
    ufw allow ${var.listen_port}/udp   comment "nabu relay"
    ufw allow ${local.probe_port}/udp  comment "nabu probe echo"
    ufw reload

    # Pull and start NABU relay container
    docker pull ${var.docker_image}

    docker run -d \
      --name nabu-relay \
      --restart unless-stopped \
      -e NABU_PATH_ID="${var.path_id}" \
      -e NABU_LISTEN_PORT="${var.listen_port}" \
      -e NABU_PROBE_PORT="${local.probe_port}" \
      -e NABU_SECRET="${var.nabu_secret}" \
      -e NABU_REGION="${var.region_label}" \
      -p ${var.listen_port}:${var.listen_port}/udp \
      -p ${local.probe_port}:${local.probe_port}/udp \
      ${var.docker_image}
  EOT

  nabu_config_snippet = <<-EOT
    # NABU relay endpoint — ${var.relay_name} (path-id ${var.path_id})
    [[relays]]
    name        = "${var.relay_name}"
    addr        = "${var.public_ip != "" ? "${var.public_ip}:${var.listen_port}" : "<PENDING>:${var.listen_port}"}"
    path_id     = ${var.path_id}
    region      = "${var.region_label}"
    probe_port  = ${local.probe_port}
  EOT
}
